export enum MiscEnum {
    WORKSPACE_ACTIONS_BLOCK = 'workspace-actions',
    SAVE_WORKSPACE_BUTTON = 'Save',
    SAVE_WORKSPACE_ACTION_ID ='save-workspace',
    SPACE_ACTIONS_BLOCK = 'workspace-actions',
    GET_SPACES_BUTTON = 'Get Spaces',
    GET_SPACES_ACTION_ID ='get-spaces',
    GET_FOLDERS_BUTTON = 'Get Folders',
    GET_FOLDERS_ACTION_ID ='get-folders',
    FOLDER_ACTIONS_BLOCK = 'workspace-actions',
    GET_LISTS_BUTTON = 'Get Lists',
    GET_LISTS_ACTION_ID ='get-lists',
    LIST_ACTIONS_BLOCK = 'workspace-actions',
    GET_TASKS_BUTTON = 'Get Tasks',
    GET_TASKS_ACTION_ID ='get-tasks',
    TASK_ACTIONS_BLOCK = 'task-actions',
	VIEW_TASK_BUTTON = 'View',
    VIEW_TASK_ACTION_ID = 'view-task',
    EDIT_TASK_BUTTON = 'Edit',
    EDIT_TASK_ACTION_ID = 'edit-task',
    SHARE_TASK_BUTTON = 'Share',
    SHARE_TASK_ACTION_ID = 'share-task',
    DELETE_TASK_BUTTON = 'Delete',
    DELETE_TASK_ACTION_ID = 'delete-task',
    SUBSCRIBE_TASK_BUTTON = 'Subscribe',
    SUBSCRIBE_TASK_ACTION_ID = 'subscribe-task',
    DELETE_SPACE_BUTTON = 'Delete',
    DELETE_SPACE_ACTION_ID = 'delete-space',
    DELETE_FOLDER_BUTTON = 'Delete',
    DELETE_FOLDER_ACTION_ID = 'delete-folder',
    DELETE_LIST_BUTTON = 'Delete',
    DELETE_LIST_ACTION_ID = 'delete-list',

}
