export enum ModalsEnum {
    CREATE_TASK = 'create-task',
    CREATE_TASK_WITH_ROOM = 'create-task-with-room',
    CREATE_TASK_LABEL = 'Crete Task',
    CREATE_TASK_WITH_ROOM_LABEL= 'Create Task & Room of Assignnees',
    TASK_NAME_INPUT_LABEL = 'Enter Task Name',
    TASK_NAME_INPUT_LABEL_DEFAULT = 'enter the task name here',
    TASK_NAME_INPUT = 'task-name',
    TASK_NAME_BLOCK = 'task-name-block',
    TASK_DESCRIPTION_BLOCK = 'task-description-block',
    TASK_DESCRIPTION_INPUT_LABEL = 'Enter Task Description',
    TASK_DESCRIPTION_INPUT_LABEL_DEFAULT = 'enter the task description here',
    TASK_DESCRIPTION_INPUT = 'task-description',
    CODE_VIEW = 'code-view',
    VIEW_FILE_ACTION = 'view-file-task',
    VIEW_FILE_ACTION_LABEL = 'View File',
    VIEW_DIFFS_ACTION_LABEL = 'View Changes',
    PULL_VIEW_LABEL = 'Pull Request',
    MERGE_PULL_REQUEST_ACTION = 'merge-pull-request',
    MERGE_PULL_REQUEST_LABEL = 'Merge',
    COMMENT_PR_ACTION = 'comment-pull-request',
    COMMENT_PR_LABEL = 'Comment',
}
